import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { supabase, isSupabaseConfigured } from './lib/supabase';
import './styles.css';

const money = n => `₦${Number(n || 0).toLocaleString()}`;

function App(){
 const [session,setSession]=useState(null); const [mode,setMode]=useState('home'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [role,setRole]=useState('affiliate'); const [message,setMessage]=useState(''); const [offers,setOffers]=useState([]); const [stats,setStats]=useState({clicks:0,conversions:0,commission:0}); const [aiPrompt,setAiPrompt]=useState(''); const [aiResult,setAiResult]=useState(''); const [loading,setLoading]=useState(false);
 useEffect(()=>{ if(!supabase)return; supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>subscription.unsubscribe(); },[]);
 useEffect(()=>{ if(session) loadData(); },[session]);
 async function loadData(){ if(!supabase)return; const {data}=await supabase.from('affiliate_offers').select('*').eq('active',true).order('created_at',{ascending:false}); if(data)setOffers(data); const {data:s}=await supabase.from('affiliate_stats').select('*').eq('user_id',session.user.id).maybeSingle(); if(s)setStats(s); }
 async function auth(){setMessage(''); if(!supabase){setMessage('Connect the BayLINK Affiliates Supabase project in Netlify environment variables first.');return;} setLoading(true); let r; if(mode==='signup'){r=await supabase.auth.signUp({email,password,options:{data:{display_name:name,requested_role:role}}});}else{r=await supabase.auth.signInWithPassword({email,password});} setLoading(false); setMessage(r.error?.message || (mode==='signup'?'Check your email to confirm your account.':'Welcome back.')); if(r.data?.session)setSession(r.data.session);}
 async function askAI(){setAiResult('');setLoading(true); try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:aiPrompt})}); const j=await r.json(); setAiResult(j.response||j.error||'No result.');}catch(e){setAiResult('AI service is not available yet. Enable Netlify AI on this site.');}setLoading(false);}
 async function referral(offer){if(!supabase||!session)return; const code=`${session.user.id.slice(0,8)}-${offer.id}`; await supabase.from('affiliate_clicks').insert({offer_id:offer.id,affiliate_id:session.user.id,referral_code:code}); await navigator.clipboard?.writeText(`${location.origin}/offer/${offer.id}?ref=${code}`); setMessage('Referral link copied.');}
 return <div className="app"><header><div className="brand">Bay<span>LINK</span> <small>Affiliate</small></div><nav><button onClick={()=>setMode('home')}>Home</button>{session&&<button onClick={()=>setMode('dashboard')}>Dashboard</button>}<button onClick={()=>setMode('businesses')}>Businesses</button><button onClick={()=>setMode('ai')}>AI Scout</button>{session?<button className="outline" onClick={()=>supabase.auth.signOut()}>Logout</button>:<button className="primary" onClick={()=>setMode('login')}>Join / Login</button>}</nav></header>
 <main>{mode==='home'&&<><section className="hero"><div><p className="eyebrow">AFRICAN BUSINESS × AFFILIATE GROWTH</p><h1>Turn connections into <span>income.</span></h1><p>BayLINK helps businesses find customers and gives affiliates powerful tools to promote real products and earn commissions.</p><div className="actions"><button className="primary" onClick={()=>{setRole('affiliate');setMode('signup')}}>Become an Affiliate</button><button className="outline" onClick={()=>{setRole('business');setMode('signup')}}>List My Business</button></div></div><div className="heroCard"><b>Affiliate engine</b><strong>5%+</strong><span>Flexible commissions per offer</span><hr/><span>✓ Referral tracking</span><span>✓ Conversion reporting</span><span>✓ Secure payouts</span></div></section><section className="grid"><article><b>For Affiliates</b><h3>Discover offers</h3><p>Get unique referral links and track clicks, conversions and earnings.</p></article><article><b>For Businesses</b><h3>Find promoters</h3><p>Put your products in front of motivated affiliates and customers.</p></article><article><b>AI Scout</b><h3>Find opportunities</h3><p>Use our AI assistant to identify promising businesses and affiliate opportunities.</p></article></section></>}
 {mode==='login'||mode==='signup'?<section className="auth card"><h2>{mode==='signup'?'Create your BayLINK account':'Welcome back'}</h2>{mode==='signup'&&<><input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}><option value="affiliate">Affiliate</option><option value="business">Business</option></select></>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary wide" disabled={loading} onClick={auth}>{loading?'Please wait…':mode==='signup'?'Create account':'Login'}</button><p>{message}</p><button className="link" onClick={()=>setMode(mode==='signup'?'login':'signup')}>{mode==='signup'?'Already have an account? Login':'New here? Create an account'}</button></section>:null}
 {mode==='dashboard'&&<section><div className="sectionHead"><div><p className="eyebrow">YOUR DASHBOARD</p><h2>Welcome, {session?.user?.user_metadata?.display_name||session?.user?.email}</h2></div></div><div className="stats"><div><span>Clicks</span><strong>{stats.clicks}</strong></div><div><span>Conversions</span><strong>{stats.conversions}</strong></div><div><span>Commission</span><strong>{money(stats.commission)}</strong></div></div><h3>Available offers</h3><div className="offers">{offers.length?offers.map(o=><article className="offer" key={o.id}><b>{o.business_name}</b><h3>{o.title}</h3><p>{o.description}</p><strong>{o.commission_rate}% commission</strong><button className="primary" onClick={()=>referral(o)}>Get referral link</button></article>):<div className="card"><p>No offers published yet. Businesses can create offers from their dashboard.</p></div>}</div></section>}
 {mode==='businesses'&&<section><p className="eyebrow">PARTNER BUSINESSES</p><h2>Offers built for promotion</h2><div className="offers">{offers.map(o=><article className="offer" key={o.id}><b>{o.business_name}</b><h3>{o.title}</h3><p>{o.description}</p><strong>{o.commission_rate}% commission</strong></article>)}{!offers.length&&<div className="card"><p>Business offers will appear here when partners publish them.</p></div>}</div></section>}
 {mode==='ai'&&<section className="ai"><p className="eyebrow">BAYLINK AI SCOUT</p><h2>Find businesses & affiliate opportunities</h2><p>Describe the market, location, product category or type of business you want to target. The AI will turn your request into a practical prospecting plan.</p><textarea value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)} placeholder="Example: Find small businesses in Nigeria that could benefit from affiliate marketing for fashion and beauty products."/><button className="primary" disabled={!aiPrompt||loading} onClick={askAI}>{loading?'Researching…':'Ask BayLINK AI'}</button>{aiResult&&<pre className="aiResult">{aiResult}</pre>}</section>}
 </main><footer>© 2026 BayLINK Affiliate · Built for businesses and affiliates.</footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
